# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.8"

before_install:
  # work around https://github.com/travis-ci/travis-ci/issues/8363
  - pyenv install 3.8.10
  - pyenv global system 3.8.10

env:
  - TOX_ENV=py38-django-40

matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
